sudo: required
services: docker

before_install:
  - docker build -t tlonist/bluemarlin2 .
  - docker push tlonist/bluemarlin2

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: bluemarlin2
  env: Bluemarlin2-env
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY