sudo: required
language: generic
services: docker

before_install:
  - docker build -t tlonist/bluemarlin2:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tlonist/bluemarlin2:latest

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: bluemarlin2
  env: Bluemarlin2-env
  bucket_name: elasticbeanstalk-ap-northeast-2-734004190163
  bucket_path: bluemarlin2-multi
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY