sudo: required
language: generic
services: docker

before_install:
  - docker build -t tlonist/bluemarlin2 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tlonist/bluemarlin2

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: bluemarlin2
  env: Bluemarlin2-env-1
  bucket_name: elasticbeanstalk-eu-central-1-734004190163
  bucket_path: docker-bluemarlin2
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY